package cli

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/justin06lee/caveira/internal/fabricate"
)

func TestWriteMailmapSkeleton(t *testing.T) {
	discovered := []fabricate.DiscoveredIdentity{
		{Identity: fabricate.Identity{Name: "justin06lee", Email: "hi@justin06lee.dev"}, Commits: 131},
		{Identity: fabricate.Identity{Name: "justin06lee", Email: "justin.leehuiyun@gmail.com"}, Commits: 1},
	}
	var buf bytes.Buffer
	writeMailmapSkeleton(&buf, discovered)
	got := buf.String()
	want := "# .mailmap skeleton generated by `cav interrogate --emit-mailmap`\n" +
		"# One line per identity discovered in history. Caveira does not guess which\n" +
		"# identities belong to the same person — to unify a drifted identity, merge its\n" +
		"# lines onto the canonical one, e.g.:\n" +
		"#   Proper Name <canonical@email> <other@email>\n" +
		"justin06lee <hi@justin06lee.dev>\n" +
		"justin06lee <justin.leehuiyun@gmail.com>\n"
	if got != want {
		t.Fatalf("writeMailmapSkeleton output mismatch:\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestWriteMailmapSkeleton_EmptyHistory(t *testing.T) {
	var buf bytes.Buffer
	writeMailmapSkeleton(&buf, nil)
	if !strings.Contains(buf.String(), "# .mailmap skeleton") {
		t.Fatalf("empty history should still print the comment header:\n%s", buf.String())
	}
}

func TestCommitCount(t *testing.T) {
	if got := commitCount(1); got != "1 commit" {
		t.Fatalf("commitCount(1) = %q, want \"1 commit\"", got)
	}
	if got := commitCount(5); got != "5 commits" {
		t.Fatalf("commitCount(5) = %q, want \"5 commits\"", got)
	}
	if got := commitCount(0); got != "0 commits" {
		t.Fatalf("commitCount(0) = %q, want \"0 commits\"", got)
	}
}

func TestWriteIdentityReport_PlayersAndModels(t *testing.T) {
	discovered := []fabricate.DiscoveredIdentity{
		{Identity: fabricate.Identity{Name: "justin06lee", Email: "hi@justin06lee.dev"}, Commits: 131},
		{Identity: fabricate.Identity{Name: "justin06lee", Email: "justin.leehuiyun@gmail.com"}, Commits: 1},
	}
	models := []fabricate.Identity{{Name: "Claude", Email: "noreply@anthropic.com"}}
	var buf bytes.Buffer
	writeIdentityReport(&buf, "/tmp/caveira", true, discovered, models)
	got := buf.String()
	for _, want := range []string{
		"/tmp/caveira", ".mailmap applied",
		"Players (2):", "hi@justin06lee.dev", "131 commits",
		"justin.leehuiyun@gmail.com", "1 commit",
		"AI models", "noreply@anthropic.com",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("report missing %q:\n%s", want, got)
		}
	}
}

func TestWriteIdentityReport_NoModels(t *testing.T) {
	discovered := []fabricate.DiscoveredIdentity{
		{Identity: fabricate.Identity{Name: "Solo", Email: "solo@x.com"}, Commits: 3},
	}
	var buf bytes.Buffer
	writeIdentityReport(&buf, "/tmp/r", false, discovered, nil)
	got := buf.String()
	if strings.Contains(got, "AI models") {
		t.Fatalf("no models found — the AI models section must be omitted:\n%s", got)
	}
	if !strings.Contains(got, "no .mailmap") {
		t.Fatalf("expected the \"no .mailmap\" header note:\n%s", got)
	}
}

func TestWriteIdentityReport_ColumnsAligned(t *testing.T) {
	discovered := []fabricate.DiscoveredIdentity{
		{Identity: fabricate.Identity{Name: "Al", Email: "a@x.com"}, Commits: 9},
		{Identity: fabricate.Identity{Name: "Bartholomew", Email: "bartholomew@example.com"}, Commits: 2},
	}
	var buf bytes.Buffer
	writeIdentityReport(&buf, "/tmp/r", false, discovered, nil)
	var col1, col2 int
	for _, line := range strings.Split(buf.String(), "\n") {
		if strings.Contains(line, "a@x.com") {
			col1 = strings.Index(line, "9 commits")
		}
		if strings.Contains(line, "bartholomew@example.com") {
			col2 = strings.Index(line, "2 commits")
		}
	}
	if col1 <= 0 || col2 <= 0 {
		t.Fatalf("could not locate both player lines:\n%s", buf.String())
	}
	if col1 != col2 {
		t.Fatalf("commit-count column not aligned: col1=%d col2=%d\n%s", col1, col2, buf.String())
	}
}

func TestWriteIdentityReport_EmptyHistory(t *testing.T) {
	var buf bytes.Buffer
	writeIdentityReport(&buf, "/tmp/empty", false, nil, nil)
	got := buf.String()
	if !strings.Contains(got, "No commits found") {
		t.Fatalf("empty history should print a friendly line:\n%s", got)
	}
	if strings.Contains(got, "Players (") {
		t.Fatalf("empty history must not print a Players section:\n%s", got)
	}
}

func TestIntegration_Interrogate_ReportsIdentitiesAndModels(t *testing.T) {
	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("git not on PATH")
	}
	src := t.TempDir()
	if out, err := exec.Command("git", "-C", src, "init").CombinedOutput(); err != nil {
		t.Fatalf("git init: %v: %s", err, out)
	}
	commit := func(name, email, file, message string) {
		t.Helper()
		if err := os.WriteFile(filepath.Join(src, file), []byte("x\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		for _, args := range [][]string{{"add", file}, {"commit", "-m", message}} {
			cmd := exec.Command("git", append([]string{"-C", src}, args...)...)
			cmd.Env = append(os.Environ(),
				"GIT_AUTHOR_NAME="+name, "GIT_AUTHOR_EMAIL="+email,
				"GIT_COMMITTER_NAME="+name, "GIT_COMMITTER_EMAIL="+email)
			if out, err := cmd.CombinedOutput(); err != nil {
				t.Fatalf("git %v: %v: %s", args, err, out)
			}
		}
	}
	// Drifted human identity: same name, two emails (2 commits + 1 commit).
	commit("justin06lee", "hi@justin06lee.dev", "a.go", "feat: a")
	commit("justin06lee", "hi@justin06lee.dev", "b.go", "feat: b")
	// A commit crediting an AI model as co-author.
	commit("justin06lee", "justin.leehuiyun@gmail.com", "c.go",
		"docs: c\n\nCo-Authored-By: Claude <noreply@anthropic.com>")

	var out, errOut bytes.Buffer
	if code := RunWithArgs([]string{"interrogate", "--repo", src}, &out, &errOut); code != 0 {
		t.Fatalf("interrogate exited %d; stderr=%q", code, errOut.String())
	}
	got := out.String()
	for _, want := range []string{
		"hi@justin06lee.dev", "justin.leehuiyun@gmail.com",
		"2 commits", "1 commit",
		"AI models", "noreply@anthropic.com",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("interrogate report missing %q:\n%s", want, got)
		}
	}

	// --emit-mailmap: one line per human identity, AI model excluded.
	var mmOut, mmErr bytes.Buffer
	if code := RunWithArgs([]string{"interrogate", "--repo", src, "--emit-mailmap"}, &mmOut, &mmErr); code != 0 {
		t.Fatalf("interrogate --emit-mailmap exited %d; stderr=%q", code, mmErr.String())
	}
	mm := mmOut.String()
	if !strings.Contains(mm, "justin06lee <hi@justin06lee.dev>") ||
		!strings.Contains(mm, "justin06lee <justin.leehuiyun@gmail.com>") {
		t.Fatalf("skeleton missing a human identity line:\n%s", mm)
	}
	if strings.Contains(mm, "noreply@anthropic.com") {
		t.Fatalf("skeleton must exclude AI models:\n%s", mm)
	}
}
