package cli

import (
	"bytes"
	"strings"
	"testing"

	"github.com/justin06lee/caveira/internal/fabricate"
)

func TestWriteMailmapSkeleton(t *testing.T) {
	discovered := []fabricate.DiscoveredIdentity{
		{Identity: fabricate.Identity{Name: "justin06lee", Email: "hi@justin06lee.dev"}, Commits: 131},
		{Identity: fabricate.Identity{Name: "justin06lee", Email: "justin.leehuiyun@gmail.com"}, Commits: 1},
	}
	var buf bytes.Buffer
	writeMailmapSkeleton(&buf, discovered)
	got := buf.String()
	want := "# .mailmap skeleton generated by `cav interrogate --emit-mailmap`\n" +
		"# One line per identity discovered in history. Caveira does not guess which\n" +
		"# identities belong to the same person — to unify a drifted identity, merge its\n" +
		"# lines onto the canonical one, e.g.:\n" +
		"#   Proper Name <canonical@email> <other@email>\n" +
		"justin06lee <hi@justin06lee.dev>\n" +
		"justin06lee <justin.leehuiyun@gmail.com>\n"
	if got != want {
		t.Fatalf("writeMailmapSkeleton output mismatch:\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestWriteMailmapSkeleton_EmptyHistory(t *testing.T) {
	var buf bytes.Buffer
	writeMailmapSkeleton(&buf, nil)
	if !strings.Contains(buf.String(), "# .mailmap skeleton") {
		t.Fatalf("empty history should still print the comment header:\n%s", buf.String())
	}
}
