package cli

import (
	"fmt"
	"io"
	"unicode/utf8"

	"github.com/go-git/go-git/v5"
	"github.com/justin06lee/caveira/internal/fabricate"
	"github.com/justin06lee/caveira/internal/input"
	"github.com/spf13/cobra"
)

// writeMailmapSkeleton prints a .mailmap skeleton to out: a comment header
// followed by one "Name <email>" line per discovered identity. Caveira never
// guesses merges — the user edits the output to unify drifted identities.
func writeMailmapSkeleton(out io.Writer, discovered []fabricate.DiscoveredIdentity) {
	fmt.Fprintln(out, "# .mailmap skeleton generated by `cav interrogate --emit-mailmap`")
	fmt.Fprintln(out, "# One line per identity discovered in history. Caveira does not guess which")
	fmt.Fprintln(out, "# identities belong to the same person — to unify a drifted identity, merge its")
	fmt.Fprintln(out, "# lines onto the canonical one, e.g.:")
	fmt.Fprintln(out, "#   Proper Name <canonical@email> <other@email>")
	for _, d := range discovered {
		fmt.Fprintf(out, "%s <%s>\n", d.Name, d.Email)
	}
}

// commitCount renders n as "1 commit" or "N commits".
func commitCount(n int) string {
	if n == 1 {
		return "1 commit"
	}
	return fmt.Sprintf("%d commits", n)
}

// writeIdentityReport prints the human-readable interrogate report to out: a
// header naming the repo and .mailmap status, the players section with commit
// counts, and (only if any were found) the AI-models section.
func writeIdentityReport(out io.Writer, srcPath string, hasMailmap bool, discovered []fabricate.DiscoveredIdentity, models []fabricate.Identity) {
	mmNote := "no .mailmap"
	if hasMailmap {
		mmNote = ".mailmap applied"
	}
	fmt.Fprintf(out, "Identities in %s  (%s)\n", srcPath, mmNote)

	if len(discovered) == 0 {
		fmt.Fprintf(out, "\nNo commits found in %s.\n", srcPath)
		return
	}

	width := 0
	for _, d := range discovered {
		if n := utf8.RuneCountInString(d.Name) + utf8.RuneCountInString(d.Email) + 3; n > width {
			width = n
		}
	}
	fmt.Fprintf(out, "\nPlayers (%d):\n", len(discovered))
	for _, d := range discovered {
		label := fmt.Sprintf("%s <%s>", d.Name, d.Email)
		fmt.Fprintf(out, "  %-*s  %s\n", width, label, commitCount(d.Commits))
	}

	if len(models) > 0 {
		fmt.Fprintln(out, "\nAI models (excluded from players — co-author only):")
		for _, m := range models {
			fmt.Fprintf(out, "  %s <%s>\n", m.Name, m.Email)
		}
	}
}

// newInterrogateCmd builds the read-only `interrogate` subcommand. It has its
// own flag set and never sees the root command's --start/--end rewrite flags.
func newInterrogateCmd() *cobra.Command {
	var (
		repoFlag    string
		outDir      string
		emitMailmap bool
	)
	cmd := &cobra.Command{
		Use:   "interrogate",
		Short: "Scan a repo's history and report its identities (read-only)",
		Long: `Scan a repository's commit history and report the identities in it:
human authors with their commit counts, and AI coding models (which appear
only as Co-Authored-By trailers, never as players). Identities are unified
through the repository's .mailmap when one is present.

interrogate is read-only — it never modifies the repository.

With --emit-mailmap, print a .mailmap skeleton instead of the report: one
line per identity, ready to edit so you can unify identities that drifted
across multiple emails. Redirect it to start a .mailmap file:

  cav interrogate --repo /path/to/repo --emit-mailmap > .mailmap`,
		SilenceUsage: true,
		RunE: func(c *cobra.Command, args []string) error {
			return runInterrogate(repoFlag, outDir, emitMailmap, c.OutOrStdout())
		},
	}
	cmd.Flags().StringVar(&repoFlag, "repo", "", "path or URL of the repository to scan (required)")
	cmd.Flags().StringVar(&outDir, "out-dir", "", "parent directory for URL clones (default $CWD)")
	cmd.Flags().BoolVar(&emitMailmap, "emit-mailmap", false, "print a .mailmap skeleton instead of the report")
	_ = cmd.MarkFlagRequired("repo")
	return cmd
}

// runInterrogate resolves repoPath (local path or URL clone), scans the repo,
// and writes either the identity report or, when emitMailmap is set, a .mailmap
// skeleton. It never modifies the repository.
func runInterrogate(repoPath, outDir string, emitMailmap bool, out io.Writer) error {
	cfg := &input.Config{Repo: repoPath, OutDir: outDir}
	srcPath, _, err := acquireSource(cfg)
	if err != nil {
		return err
	}
	gitRepo, err := git.PlainOpen(srcPath)
	if err != nil {
		return fmt.Errorf("open repository %s: %w", srcPath, err)
	}
	mailmap, err := fabricate.LoadMailmap(srcPath)
	if err != nil {
		return fmt.Errorf("load .mailmap: %w", err)
	}
	discovered, err := fabricate.DiscoverIdentities(gitRepo, mailmap)
	if err != nil {
		return fmt.Errorf("scan identities: %w", err)
	}
	if emitMailmap {
		writeMailmapSkeleton(out, discovered)
		return nil
	}
	modelReport, err := fabricate.ScanModelReport(gitRepo, mailmap)
	if err != nil {
		return fmt.Errorf("scan models: %w", err)
	}
	writeIdentityReport(out, srcPath, mailmap != nil, discovered, modelReport.Models)
	return nil
}
