package cli

import (
	"fmt"
	"io"

	"github.com/justin06lee/caveira/internal/fabricate"
)

// writeMailmapSkeleton prints a .mailmap skeleton to out: a comment header
// followed by one "Name <email>" line per discovered identity. Caveira never
// guesses merges — the user edits the output to unify drifted identities.
func writeMailmapSkeleton(out io.Writer, discovered []fabricate.DiscoveredIdentity) {
	fmt.Fprintln(out, "# .mailmap skeleton generated by `cav interrogate --emit-mailmap`")
	fmt.Fprintln(out, "# One line per identity discovered in history. Caveira does not guess which")
	fmt.Fprintln(out, "# identities belong to the same person — to unify a drifted identity, merge its")
	fmt.Fprintln(out, "# lines onto the canonical one, e.g.:")
	fmt.Fprintln(out, "#   Proper Name <canonical@email> <other@email>")
	for _, d := range discovered {
		fmt.Fprintf(out, "%s <%s>\n", d.Name, d.Email)
	}
}
