import { BORDER_OPTIONS, lineChar } from "./borders";
import { boxLayout, titleInk, titleLayout } from "./compose";
import { ATTR_KEYS, inkKey, type BoxElement, type Doc, type Ink, type PaintCell } from "./model";
import { graphemeWidth } from "./text";

// Go source that rebuilds the design with lipgloss v2: every element becomes a
// lipgloss.Layer at its x/y, composited onto a canvas of the design's size.

const GO_ATTR: Record<(typeof ATTR_KEYS)[number], string> = {
  bold: "Bold",
  faint: "Faint",
  italic: "Italic",
  underline: "Underline",
  strike: "Strikethrough",
  reverse: "Reverse",
};

// JSON string literals are valid Go interpreted string literals.
const q = (s: string) => JSON.stringify(s);
const color = (c: string) => `lipgloss.Color(${q(c)})`;

function inkChain(ink: Ink, fgMethod = "Foreground", bgMethod = "Background"): string[] {
  const out: string[] = [];
  if (ink.fg) out.push(`${fgMethod}(${color(ink.fg)})`);
  if (ink.bg) out.push(`${bgMethod}(${color(ink.bg)})`);
  for (const k of ATTR_KEYS) if (ink[k]) out.push(`${GO_ATTR[k]}(true)`);
  return out;
}

export function goIdent(name: string): string {
  const parts = name.split(/[^A-Za-z0-9]+/).filter(Boolean);
  let id = parts.map((p) => p[0]!.toUpperCase() + p.slice(1)).join("");
  if (!id) id = "Design";
  if (/^\d/.test(id)) id = "Design" + id;
  return id;
}

export function toGo(doc: Doc, pkg = "designs"): string {
  const fn = goIdent(doc.name);
  const styles = new Map<string, { name: string; chain: string[] }>();
  const layers: string[] = [];
  let z = 0;

  // Plain inks are shared as named styles; an empty ink needs no style at all.
  const render = (ink: Ink, s: string): string => {
    const chain = inkChain(ink);
    if (!chain.length) return q(s);
    const key = inkKey(ink);
    let st = styles.get(key);
    if (!st) {
      st = { name: `ink${styles.size + 1}`, chain };
      styles.set(key, st);
    }
    return `${st.name}.Render(${q(s)})`;
  };

  const layer = (comment: string, content: string, x: number, y: number) => {
    layers.push(`\t\t// ${comment}\n\t\tlipgloss.NewLayer(${content}).X(${x}).Y(${y}).Z(${++z}),`);
  };

  for (const e of doc.elements) {
    if (e.hidden) continue;
    switch (e.type) {
      case "box":
        layer(e.name, boxStyle(e), e.x, e.y);
        {
          const T = titleLayout(e);
          if (T) layer(`${e.name} title`, render(titleInk(e), T.text), T.x, e.y);
        }
        break;
      case "text": {
        if (!e.text) break;
        if (!e.text.includes("\n")) {
          layer(e.name, render(e.ink, e.text), e.x, e.y);
          break;
        }
        // A styled multi-line block is padded to its widest line, like the editor draws it.
        const chain = inkChain(e.ink);
        if (e.align !== "left") chain.push(`Align(lipgloss.${e.align === "center" ? "Center" : "Right"})`);
        layer(e.name, styleExpr(chain, e.text), e.x, e.y);
        break;
      }
      case "line": {
        const ch = lineChar(e.kind, e.dir, e.char);
        const s = e.dir === "h" ? ch.repeat(Math.max(1, Math.floor(e.len / Math.max(1, graphemeWidth(ch))))) : Array(e.len).fill(ch).join("\n");
        layer(e.name, render(e.ink, s), e.x, e.y);
        break;
      }
      case "paint":
        for (const run of paintRuns(e.cells, e.x, e.y, doc.cols, doc.rows)) {
          const parts: string[] = [];
          let seg = "";
          let segInk: Ink | null = null;
          for (const c of run.cells) {
            if (segInk && inkKey(segInk) === inkKey(c)) seg += c.ch;
            else {
              if (segInk) parts.push(render(segInk, seg));
              segInk = c;
              seg = c.ch;
            }
          }
          if (segInk) parts.push(render(segInk, seg));
          layer(`${e.name} row ${run.y}`, parts.join(" +\n\t\t\t"), run.x, run.y);
        }
        break;
    }
  }

  const decl = [...styles.values()]
    .map((s) => `\t\t${s.name} = lipgloss.NewStyle().${s.chain.join(".")}`)
    .join("\n");

  return `// Code generated by the caveira cell editor from designs/${doc.name}.cells.json.

package ${pkg}

import "charm.land/lipgloss/v2"

// ${fn} draws the "${doc.name}" design, ${doc.cols}×${doc.rows} cells.
func ${fn}() string {
${decl ? `\tvar (\n${decl}\n\t)\n\n` : ""}\tlayers := []*lipgloss.Layer{
${layers.join("\n")}
\t}
\treturn lipgloss.NewCanvas(${doc.cols}, ${doc.rows}).Compose(lipgloss.NewCompositor(layers...)).Render()
}
`;
}

function boxStyle(e: BoxElement): string {
  const L = boxLayout(e);
  const chain: string[] = [`Width(${e.w})`, `Height(${e.h})`];
  if (e.border !== "none") {
    const go = BORDER_OPTIONS.find((o) => o.kind === e.border)!.go;
    const all = e.sides.every(Boolean);
    chain.push(all ? `Border(${go})` : `Border(${go}, ${e.sides.join(", ")})`);
    chain.push(...inkChain({ fg: e.borderInk.fg, bg: e.borderInk.bg }, "BorderForeground", "BorderBackground"));
  }
  chain.push(...inkChain(e.ink));
  const [t, r, b, l] = e.padding;
  if (t || r || b || l) chain.push(t === b && r === l ? (t === r ? `Padding(${t})` : `Padding(${t}, ${r})`) : `Padding(${t}, ${r}, ${b}, ${l})`);
  if (e.align !== "left") chain.push(`AlignHorizontal(lipgloss.${e.align === "center" ? "Center" : "Right"})`);
  if (e.valign !== "top") chain.push(`AlignVertical(lipgloss.${e.valign === "middle" ? "Center" : "Bottom"})`);
  // Pre-wrap and clip text that would overflow, since Height only grows a block.
  const text = L.overflow ? L.lines.join("\n") : e.text;
  return styleExpr(chain, text);
}

function styleExpr(chain: string[], text: string): string {
  if (!chain.length) return `lipgloss.NewStyle().Render(${q(text)})`;
  return `lipgloss.NewStyle().\n\t\t\t${chain.join(".\n\t\t\t")}.\n\t\t\tRender(${q(text)})`;
}

interface Run {
  x: number;
  y: number;
  cells: PaintCell[];
}

// Contiguous horizontal runs of painted cells, clipped to the canvas, so gaps
// stay transparent instead of becoming spaces.
function paintRuns(cells: Record<string, PaintCell>, ox: number, oy: number, cols: number, rows: number): Run[] {
  const byRow = new Map<number, Map<number, PaintCell>>();
  for (const k in cells) {
    const [cx, cy] = k.split(",").map(Number) as [number, number];
    const x = ox + cx;
    const y = oy + cy;
    if (x < 0 || y < 0 || x >= cols || y >= rows) continue;
    let row = byRow.get(y);
    if (!row) byRow.set(y, (row = new Map()));
    row.set(x, cells[k]!);
  }
  const runs: Run[] = [];
  for (const y of [...byRow.keys()].sort((a, b) => a - b)) {
    const row = byRow.get(y)!;
    const xs = [...row.keys()].sort((a, b) => a - b);
    let run: Run | null = null;
    let next = -1;
    for (const x of xs) {
      if (x < next) continue; // covered by a wide character
      const c = row.get(x)!;
      if (!run || x !== next) {
        run = { x, y, cells: [] };
        runs.push(run);
      }
      run.cells.push(c);
      next = x + Math.max(1, graphemeWidth(c.ch));
      if (next > cols) break;
    }
  }
  return runs;
}
